[theme]
# Primary accent color for interactive elements
primaryColor = "#6366f1"

# Background color for the main content area
backgroundColor = "#ffffff"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = "#f0f2f6"

# Color used for almost all text
textColor = "#262730"

# Font family for all text in the app, except code blocks
font = "sans serif"

[server]
# Max size, in MB, for files uploaded with the file uploader
maxUploadSize = 10

# Enables support for websocket compression.
enableWebsocketCompression = true

[browser]
# Internet address where users should point their browsers in order to connect to the app
serverAddress = "localhost"

# Whether to send usage statistics to Streamlit.
gatherUsageStats = true

# Port where users should point their browsers in order to connect to the app.
serverPort = 8501